[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#FF005C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F8FA"
textColor = "#000000"
font = "sans serif"
